version: '3.8'

services:
  nginx:
    container_name: prod_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - prod_network
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.6'
          memory: 1G
    environment:
      ENVIRONMENT: production
      WORKERS: "1"
      DB_POOL_SIZE: 20
      DB_MAX_OVERFLOW: 5
      SYNC_SQLALCHEMY_DATABASE_URL: ${DATABASE_URL}
      ASYNC_SQLALCHEMY_DATABASE_URL: ${ASYNC_DATABASE_URL}
      REDIS_URL: redis://redis:6379
      ENABLE_METRICS: "true"
    networks:
      - prod_network
    restart: always

  redis:
    container_name: prod_redis
    image: redis:7.2-alpine
    command: ["redis-server", "--requirepass", "myStrongPassword", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
    networks:
      - prod_network
    restart: always

networks:
  prod_network:
    driver: bridge
